import type { OpenAPIObject } from '@nestjs/swagger';
import { arraySchemaReference, schemaReference } from './openapi.schemas';

type SchemaDefinition = NonNullable<
  NonNullable<OpenAPIObject['components']>['schemas']
>[string];

export const OPEN_API_SUCCESS_SCHEMAS: Record<string, SchemaDefinition> = {
  DeviceTokenController_create: schemaReference('DeviceTokenRecord'),
  DeviceTokenController_list: arraySchemaReference('DeviceTokenRecord'),
  DeviceTokenController_updateProjects: schemaReference('DeviceTokenRecord'),
  DeviceTokenController_revoke: schemaReference('DeviceTokenRecord'),
  DeviceTokenController_delete: schemaReference('DeletedResult'),
  ProjectsController_list: arraySchemaReference('Project'),
  ProjectsController_create: schemaReference('Project'),
  ProjectsController_info: arraySchemaReference('ProjectInfo'),
  ProjectsController_remove: schemaReference('DeletedResult'),
  ProjectsController_setEnabled: schemaReference('ProjectEnabledResult'),
  MetricsController_overview: schemaReference('MetricsOverview'),
  MetricsController_weekly: arraySchemaReference('WeeklyDeviceMetrics'),
  MetricsController_trend: arraySchemaReference('DailyTrendPoint'),
  DevicesController_list: arraySchemaReference('Device'),
  DevicesController_get: schemaReference('Device'),
  RbacController_createRole: schemaReference('PermissionGroup'),
  RbacController_listRoles: arraySchemaReference('PermissionGroup'),
  RbacController_updateRole: schemaReference('PermissionGroup'),
  RbacController_deleteRole: schemaReference('DeletedResult'),
  RbacController_createPermission: schemaReference('Permission'),
  RbacController_listPermissions: arraySchemaReference('Permission'),
  RbacController_deletePermission: schemaReference('DeletedResult'),
  RbacController_attachPermissionFromBody: schemaReference('AttachedResult'),
  RbacController_attachPermission: schemaReference('AttachedResult'),
  RbacController_detachPermission: schemaReference('DetachedResult'),
  RbacController_listUserRoles: arraySchemaReference('PermissionGroup'),
  RbacController_assignRoleFromBody: schemaReference('AssignedResult'),
  RbacController_assignRole: schemaReference('AssignedResult'),
  RbacController_unassignRole: schemaReference('UnassignedResult'),
  UsersController_list: arraySchemaReference('User'),
  UsersController_create: schemaReference('User'),
  UsersController_findOne: schemaReference('User'),
  UsersController_update: schemaReference('User'),
  UsersController_remove: schemaReference('DeletedResult'),
  UsersController_setPassword: schemaReference('User'),
  UsersController_setEnabled: schemaReference('UserEnabledResult'),
  AuthController_login: schemaReference('LoginResponse'),
  AuthController_me: schemaReference('AuthenticatedUser'),
  AccessTokenController_create: schemaReference('AccessTokenRecord'),
  AccessTokenController_list: arraySchemaReference('AccessTokenRecord'),
  AccessTokenController_updateProjects: schemaReference('AccessTokenRecord'),
  AccessTokenController_revoke: schemaReference('AccessTokenRecord'),
  AccessTokenController_delete: schemaReference('DeletedResult'),
  RpcController_debugOptions: schemaReference('RpcDebugOptions'),
  RpcController_debugInvoke: schemaReference('InvokeResponse'),
  RpcController_invoke: schemaReference('InvokeResponse'),
  RpcController_clientQueue: schemaReference('ClientQueueResponse'),
  MonitorController_list: schemaReference('RequestLogPage'),
  MonitorController_requestOptions: schemaReference('RequestOptions'),
  MonitorController_detail: schemaReference('RequestDetail'),
  SystemLogsController_list: schemaReference('SystemLogPage'),
};

export const NOT_FOUND_OPERATION_IDS = new Set([
  'DeviceTokenController_updateProjects',
  'DeviceTokenController_revoke',
  'DeviceTokenController_delete',
  'ProjectsController_setEnabled',
  'DevicesController_get',
  'RbacController_updateRole',
  'RbacController_deleteRole',
  'RbacController_deletePermission',
  'RbacController_attachPermissionFromBody',
  'RbacController_attachPermission',
  'RbacController_detachPermission',
  'RbacController_listUserRoles',
  'RbacController_assignRoleFromBody',
  'RbacController_assignRole',
  'RbacController_unassignRole',
  'UsersController_findOne',
  'UsersController_update',
  'UsersController_remove',
  'UsersController_setPassword',
  'UsersController_setEnabled',
  'AccessTokenController_updateProjects',
  'AccessTokenController_revoke',
  'AccessTokenController_delete',
  'MonitorController_detail',
]);

export const CONFLICT_OPERATION_IDS = new Set([
  'ProjectsController_create',
  'RbacController_createRole',
  'RbacController_updateRole',
  'RbacController_createPermission',
  'RbacController_attachPermissionFromBody',
  'RbacController_attachPermission',
  'RbacController_assignRoleFromBody',
  'RbacController_assignRole',
  'UsersController_create',
]);
